let a;
alert("Press F12")
a = " " + 1 + 0; 
console.log('" " + 1 + 0 =' + a);
a = " " - 1 + 0; 
console.log('" " - 1 + 0 =' + a);
a = true + false; 
console.log('true + false =' + a);
a = 6 / '3'; 
console.log('6 / "3" =' + a);
a = '2' * '3'; 
console.log('"2" * "3" =' + a);
a = 4 + 5 + "px"; 
console.log('4 + 5 + "px" =' + a);
a = "$" + 4 + 5; 
console.log('"$" + 4 + 5 =' + a);
a = 4 - "2"; 
console.log('"4" - 2 =' + a);
a = "4px" - 2; 
console.log('"4px" - 2 =' + a);
a = 7 / 0; 
console.log('7 / 0 =' + a);
a = "  -9\n" + 5;
console.log('"  -9\n" + 5 = ' + a);
a = "  -9\n" - 5;
console.log('"  -9\n" - 5 = ' + a);
a = 5 && 2;
console.log('5 && 2 = ' + a);
a = 2 && 5;
console.log('2 && 5 = ' + a);
a = 5 || 0;
console.log('5 || 0 = ' + a);
a = 0 || 5;
console.log('0 || 5 = ' + a);
a = null + 1;
console.log('null + 1 = ' + a);
a = undefined + 1;
console.log('undefined + 1 = ' + a);
a = null == "\n0\n";
console.log('null == "\n0\n" =' + a);
a = +null == +"\n0\n";
console.log('+null == +"\n0\n" =' + a);
